### ISSUE TITLE
grunt pre-commit doesn't work on Windows

### ISSUE THREAD

**Issue by adamhope** [twlevelup/watch_edition#2]
The pre-commit work on windows

Grunt exec is unable to run jscs on Windows, I believe this is due to the path or context in which exec runs.

**Comment by watsonarw** [comment]
Diagnosis: This seems to be an issue with wildcard globs (`*`) rather than an issue with jscs.

Running the `jscs grunt/*.js ` directly in git bash works, and running `jscs grunt/` within the grunt exec context also works. The same happens when swapping `jscs` with `jshint` in the above scenarios. However, running `jscs grunt/*.js` within the `grunt exec` or `npm run` contexts, it fails. It also fails in standard windows `cmd prompt`.

http://stackoverflow.com/a/30114333

**Comment by watsonarw** [comment]
`grunt pre-commit` should now work on Windows after a0f920b665f586e4f3fca05b6b8fceeaf42ad7e6

This replaces `grunt exec:jscs` with `grunt jscs` which has better support for wildcard globs.
